In [329]:
import pandas as pd
import numpy as np
from matplotlib.pyplot import plot

In [330]:
house_prices = pd.read_csv("data/Housing.csv")

### Since there are non-numeric from the dataset we must first convert em into numbers

In [331]:
house_prices.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished

In [332]:
non_numeric_cols = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']

house_prices[non_numeric_cols] = house_prices[non_numeric_cols].apply(lambda col: col.map({'yes': 1, 'no': 0}))

house_prices = pd.get_dummies(house_prices, columns=['furnishingstatus'],
                              drop_first=True)  # Drop the first furnishingstatus, it will become the baseline later
bool_cols = house_prices.select_dtypes(include='bool').columns
house_prices[bool_cols] = house_prices[bool_cols].astype(int)
house_prices

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,0,1
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1,0
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,0,1
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,0,1

### Now separate the training data from the label data, the price is the label

In [333]:
print(house_prices.isnull().sum())  # Check if there are any null values first, since wala then proceed

price                              0
area                               0
bedrooms                           0
bathrooms                          0
stories                            0
mainroad                           0
guestroom                          0
basement                           0
hotwaterheating                    0
airconditioning                    0
parking                            0
prefarea                           0
furnishingstatus_semi-furnished    0
furnishingstatus_unfurnished       0
dtype: int64

In [334]:
# X train
X = house_prices.iloc[:, 1:].values
# y true
y = house_prices.iloc[:, 0].values
# Split the data for training and testing ( same sa digit recognition system ko )
# 80% of the data will be used for the training and the rest is for testing
shuffle_idx = np.random.permutation(len(X))
X = X[shuffle_idx]
y = y[shuffle_idx]

train_percent_index = int(0.8 * len(X))
X_train, X_test = X[:train_percent_index], X[train_percent_index:]
y_train, y_test = y[:train_percent_index], y[train_percent_index:]

# Scale not Normalize
# Kasi tangina naga explode gradients since there are scenarios where the input are smaller than the label
# And once the grads are updated it just explodes ( the weight are large as fuck )
# That's why when you try to compute for the loss umaabot ng trillions
X_mean = X_train.mean(axis=0)
X_std = X_train.std(axis=0)

y_mean = y_train.mean()
y_std = y_train.std()

X_train = (X_train - X_mean) / X_std
X_test = (X_test - X_mean) / X_std

y_train = (y_train - y_mean) / y_std
y_test = (y_test - y_mean) / y_std

# Shuffle timee
shuffle_idx = np.random.permutation(len(X_train))
X_train = X_train[shuffle_idx]
y_train = y_train[shuffle_idx]
X_train

array([[-0.48570068,  0.040821  , -0.56786585, ..., -0.54908336,
         1.19822961, -0.70589078],
       [-1.13977821,  0.040821  , -0.56786585, ..., -0.54908336,
        -0.83456459,  1.41664976],
       [ 1.01149149, -1.32825269, -0.56786585, ..., -0.54908336,
         1.19822961, -0.70589078],
       ...,
       [-0.61340371, -1.32825269, -0.56786585, ..., -0.54908336,
        -0.83456459,  1.41664976],
       [-1.03450331,  0.040821  , -0.56786585, ..., -0.54908336,
        -0.83456459,  1.41664976],
       [ 0.3935736 ,  1.4098947 ,  3.49097856, ..., -0.54908336,
         1.19822961, -0.70589078]], shape=(436, 13))

In [335]:
learning_rate = 0.1
W = []
B = []

layer_sizes = [13, 16, 1]  # input, hidden, output
np.shape(X_train)
# Init Weights and Biases
for n in range(len(layer_sizes) - 1):
    _in = layer_sizes[n]
    _out = layer_sizes[n + 1]
    W.append(np.random.randn(_in, _out) * np.sqrt(2.0 / _in))
    B.append(np.zeros((1, _out)))

Z = [None] * (len(layer_sizes) - 1)  # Summation aft mat multiplication is applied
H = [None] * (len(layer_sizes) - 1)  # Activation
len(W)
# self.__W1 = np.random.randn(784, 256) * np.sqrt(2.0 / 784)
# self.__B1 = np.zeros((1, 256))

2

In [336]:
def relu(x_array):
    return np.maximum(0, x_array)


def unscale_y(y_scaled):
    """ The scaled was [-3, 3] lang so unscale para mabalik sa orig scale """
    return (y_scaled * y_std) + y_mean


def relu_derivative(z):
    return (z > 0).astype(float)


def MSE(y_pred, y_true):
    return np.square(np.subtract(y_true, y_pred)).mean()


def MSE_derivative(y_true, y_pred):  # Na-cow
    """
    Calculates the gradient of MSE with respect to y_pred.
    Formula: 2/n * (y_pred - y_true)
    """
    y_true = y_true.reshape(y_pred.shape)
    n = y_true.size
    return 2 * (y_pred - y_true) / n


def evaluate():
    y_pred_scaled = forward_pass(X_test)
    y_pred = unscale_y(y_pred_scaled.ravel())
    y_true = unscale_y(y_test)

    rmse = np.sqrt(np.mean((y_pred - y_true) ** 2))
    mae = np.mean(np.abs(y_pred - y_true))

    total_squared_error = np.sum((y_true - y_pred) ** 2) # How wrong our model is
    dumb_guessed_tse = np.sum((y_true - np.mean(y_true)) ** 2) # How wrong the "guessed mean"
    r2 = 1 - (total_squared_error / dumb_guessed_tse)
    return rmse, mae, r2


def update_params(grads):
    w, b = grads
    for i in (range(len(W))):
        W[i] -= w[i] * learning_rate
        B[i] -= b[i] * learning_rate


def forward_pass(X_batch):
    h = X_batch
    for i in range(len(W)):
        Z[i] = h @ W[i] + B[i]
        H[i] = relu(Z[i]) if i < len(W) - 1 else Z[i]
        h = H[i]
    return h  # y_pred


def back_propagation(X_batch, y_pred, y_true):
    """ There is probably a simpler/better way of doing this but since I only had 5 hours of sleep I won't overthink it. """
    dL_dy = MSE_derivative(y_true, y_pred)

    dL_dz = dL_dy  # Pass the y_pred; could've passed the y_pred var instead of the Z but it's just the same
    dL_dW = [None] * len(W)
    dL_dB = [None] * len(W)
    # Start the loop from the max since ts is not forward pass
    for i in reversed(range(len(W))):
        input_h = X_batch if i == 0 else H[i - 1]  # Input activation
        dL_dW[i] = (input_h.T @ dL_dz) / X_batch.shape[0]
        dL_dB[i] = np.sum(dL_dz, axis=0, keepdims=True) / X_batch.shape[0]
        if i > 0:
            dL_dz = (dL_dz @ W[i].T) * relu_derivative(Z[i - 1])
    return dL_dW, dL_dB


def train(epochs=200, batch_size=64):
    n_samples = X_train.shape[0]
    n_batches = n_samples // batch_size

    for e in range(epochs):
        indices = np.random.permutation(n_samples)
        X_shuffled = X_train[indices]
        y_shuffled = y_train[indices]

        losses = 0
        for batch in range(n_batches):
            start_idx = batch * batch_size
            end_idx = start_idx + batch_size

            X_batch = X_shuffled[start_idx:end_idx]
            y_batch = y_shuffled[start_idx:end_idx]

            y_hat = forward_pass(X_batch)

            losses += MSE(y_hat, y_batch,)

            grads = back_propagation(X_batch, y_hat, y_batch)
            update_params(grads)
        losses_mean = losses / n_batches
        rmse, mae, r2 = evaluate()

        print(
            f"Epoch {e + 1}/{epochs} - "
            f"Loss: {losses_mean:.4f} - "
            f"RMSE: {rmse:,.0f} - "
            f"MAE: {mae:,.0f} - "
            f"R2: {r2:.4f} - "
        )

In [337]:
train()

Epoch 1/200 - Loss: 2.1218 - RMSE: 1,528,562 - MAE: 1,167,493 - R2: 0.2695 -
Epoch 2/200 - Loss: 2.0314 - RMSE: 1,497,964 - MAE: 1,141,592 - R2: 0.2985 -
Epoch 3/200 - Loss: 1.9091 - RMSE: 1,474,040 - MAE: 1,120,290 - R2: 0.3207 -
Epoch 4/200 - Loss: 1.9219 - RMSE: 1,449,548 - MAE: 1,099,824 - R2: 0.3431 -
Epoch 5/200 - Loss: 1.9330 - RMSE: 1,429,639 - MAE: 1,082,421 - R2: 0.3610 -
Epoch 6/200 - Loss: 1.9444 - RMSE: 1,411,901 - MAE: 1,067,415 - R2: 0.3768 -
Epoch 7/200 - Loss: 1.8582 - RMSE: 1,394,618 - MAE: 1,052,189 - R2: 0.3919 -
Epoch 8/200 - Loss: 1.9396 - RMSE: 1,380,329 - MAE: 1,040,944 - R2: 0.4043 -
Epoch 9/200 - Loss: 1.8569 - RMSE: 1,367,290 - MAE: 1,031,026 - R2: 0.4155 -
Epoch 10/200 - Loss: 1.8730 - RMSE: 1,354,838 - MAE: 1,021,961 - R2: 0.4261 -
Epoch 11/200 - Loss: 1.8689 - RMSE: 1,343,914 - MAE: 1,013,730 - R2: 0.4353 -
Epoch 12/200 - Loss: 1.8581 - RMSE: 1,333,961 - MAE: 1,005,121 - R2: 0.4437 -
Epoch 13/200 - Loss: 1.7458 - RMSE: 1,325,379 - MAE: 997,790 - R2: 0.4508 -
Epoch 14/200 - Loss: 1.7194 - RMSE: 1,317,009 - MAE: 990,655 - R2: 0.4577 -
Epoch 15/200 - Loss: 1.7735 - RMSE: 1,309,242 - MAE: 983,719 - R2: 0.4641 -
Epoch 16/200 - Loss: 1.7596 - RMSE: 1,301,143 - MAE: 976,622 - R2: 0.4707 -
Epoch 17/200 - Loss: 1.7698 - RMSE: 1,294,492 - MAE: 970,973 - R2: 0.4761 -
Epoch 18/200 - Loss: 1.7717 - RMSE: 1,287,989 - MAE: 965,017 - R2: 0.4813 -
Epoch 19/200 - Loss: 1.7409 - RMSE: 1,281,806 - MAE: 959,144 - R2: 0.4863 -
Epoch 20/200 - Loss: 1.7465 - RMSE: 1,275,927 - MAE: 953,762 - R2: 0.4910 -
Epoch 21/200 - Loss: 1.6438 - RMSE: 1,270,213 - MAE: 948,271 - R2: 0.4956 -
Epoch 22/200 - Loss: 1.8382 - RMSE: 1,264,853 - MAE: 943,367 - R2: 0.4998 -
Epoch 23/200 - Loss: 1.7102 - RMSE: 1,260,322 - MAE: 939,225 - R2: 0.5034 -
Epoch 24/200 - Loss: 1.6047 - RMSE: 1,255,561 - MAE: 935,041 - R2: 0.5071 -
Epoch 25/200 - Loss: 1.7683 - RMSE: 1,251,192 - MAE: 932,101 - R2: 0.5106 -
Epoch 26/200 - Loss: 1.7856 - RMSE: 1,247,018 - MAE: 929,409 - R2: 0.5138 -
Epoch 27/200 - Loss: 1.7314 - RMSE: 1,243,096 - MAE: 926,844 - R2: 0.5169 -
Epoch 28/200 - Loss: 1.7724 - RMSE: 1,239,295 - MAE: 924,350 - R2: 0.5198 -
Epoch 29/200 - Loss: 1.5466 - RMSE: 1,235,881 - MAE: 921,667 - R2: 0.5225 -
Epoch 30/200 - Loss: 1.7389 - RMSE: 1,232,225 - MAE: 919,054 - R2: 0.5253 -
Epoch 31/200 - Loss: 1.6036 - RMSE: 1,228,905 - MAE: 916,616 - R2: 0.5278 -
Epoch 32/200 - Loss: 1.7454 - RMSE: 1,225,453 - MAE: 914,036 - R2: 0.5305 -
Epoch 33/200 - Loss: 1.7119 - RMSE: 1,222,360 - MAE: 911,875 - R2: 0.5329 -
Epoch 34/200 - Loss: 1.6681 - RMSE: 1,219,267 - MAE: 909,483 - R2: 0.5352 -
Epoch 35/200 - Loss: 1.7589 - RMSE: 1,216,331 - MAE: 907,620 - R2: 0.5375 -
Epoch 36/200 - Loss: 1.6775 - RMSE: 1,213,814 - MAE: 906,075 - R2: 0.5394 -
Epoch 37/200 - Loss: 1.6815 - RMSE: 1,211,264 - MAE: 904,336 - R2: 0.5413 -
Epoch 38/200 - Loss: 1.5168 - RMSE: 1,209,187 - MAE: 902,869 - R2: 0.5429 -
Epoch 39/200 - Loss: 1.6610 - RMSE: 1,206,681 - MAE: 901,350 - R2: 0.5448 -
Epoch 40/200 - Loss: 1.7294 - RMSE: 1,204,498 - MAE: 900,361 - R2: 0.5464 -
Epoch 41/200 - Loss: 1.7252 - RMSE: 1,202,418 - MAE: 899,002 - R2: 0.5480 -
Epoch 42/200 - Loss: 1.6819 - RMSE: 1,200,297 - MAE: 897,434 - R2: 0.5496 -
Epoch 43/200 - Loss: 1.6850 - RMSE: 1,198,167 - MAE: 896,104 - R2: 0.5512 -
Epoch 44/200 - Loss: 1.7465 - RMSE: 1,195,630 - MAE: 894,423 - R2: 0.5531 -
Epoch 45/200 - Loss: 1.6560 - RMSE: 1,193,864 - MAE: 893,783 - R2: 0.5544 -
Epoch 46/200 - Loss: 1.6783 - RMSE: 1,191,781 - MAE: 892,221 - R2: 0.5559 -
Epoch 47/200 - Loss: 1.7492 - RMSE: 1,189,865 - MAE: 891,061 - R2: 0.5574 -
Epoch 48/200 - Loss: 1.6760 - RMSE: 1,187,760 - MAE: 889,710 - R2: 0.5589 -
Epoch 49/200 - Loss: 1.6924 - RMSE: 1,185,658 - MAE: 888,502 - R2: 0.5605 -
Epoch 50/200 - Loss: 1.6686 - RMSE: 1,183,845 - MAE: 887,330 - R2: 0.5618 -
Epoch 51/200 - Loss: 1.6268 - RMSE: 1,182,568 - MAE: 886,449 - R2: 0.5628 -
Epoch 52/200 - Loss: 1.5353 - RMSE: 1,181,050 - MAE: 885,367 - R2: 0.5639 -
Epoch 53/200 - Loss: 1.6298 - RMSE: 1,179,897 - MAE: 884,528 - R2: 0.5647 -
Epoch 54/200 - Loss: 1.6649 - RMSE: 1,178,469 - MAE: 883,492 - R2: 0.5658 -
Epoch 55/200 - Loss: 1.7152 - RMSE: 1,176,509 - MAE: 882,399 - R2: 0.5672 -
Epoch 56/200 - Loss: 1.6886 - RMSE: 1,175,126 - MAE: 881,577 - R2: 0.5683 -
Epoch 57/200 - Loss: 1.7045 - RMSE: 1,173,561 - MAE: 880,636 - R2: 0.5694 -
Epoch 58/200 - Loss: 1.6724 - RMSE: 1,171,517 - MAE: 879,419 - R2: 0.5709 -
Epoch 59/200 - Loss: 1.6805 - RMSE: 1,169,939 - MAE: 878,415 - R2: 0.5721 -
Epoch 60/200 - Loss: 1.6837 - RMSE: 1,168,107 - MAE: 877,360 - R2: 0.5734 -
Epoch 61/200 - Loss: 1.6693 - RMSE: 1,166,961 - MAE: 876,427 - R2: 0.5742 -
Epoch 62/200 - Loss: 1.5807 - RMSE: 1,165,506 - MAE: 875,515 - R2: 0.5753 -
Epoch 63/200 - Loss: 1.6774 - RMSE: 1,163,653 - MAE: 874,281 - R2: 0.5766 -
Epoch 64/200 - Loss: 1.6912 - RMSE: 1,162,506 - MAE: 873,678 - R2: 0.5775 -
Epoch 65/200 - Loss: 1.6006 - RMSE: 1,161,799 - MAE: 873,293 - R2: 0.5780 -
Epoch 66/200 - Loss: 1.7034 - RMSE: 1,160,420 - MAE: 872,533 - R2: 0.5790 -
Epoch 67/200 - Loss: 1.6613 - RMSE: 1,158,996 - MAE: 871,673 - R2: 0.5800 -
Epoch 68/200 - Loss: 1.6347 - RMSE: 1,157,550 - MAE: 870,799 - R2: 0.5811 -
Epoch 69/200 - Loss: 1.7113 - RMSE: 1,156,035 - MAE: 869,973 - R2: 0.5822 -
Epoch 70/200 - Loss: 1.7012 - RMSE: 1,154,675 - MAE: 869,126 - R2: 0.5832 -
Epoch 71/200 - Loss: 1.5742 - RMSE: 1,154,302 - MAE: 868,968 - R2: 0.5834 -
Epoch 72/200 - Loss: 1.6260 - RMSE: 1,153,146 - MAE: 868,275 - R2: 0.5843 -
Epoch 73/200 - Loss: 1.5920 - RMSE: 1,152,064 - MAE: 867,579 - R2: 0.5850 -
Epoch 74/200 - Loss: 1.6680 - RMSE: 1,150,796 - MAE: 866,619 - R2: 0.5860 -
Epoch 75/200 - Loss: 1.5030 - RMSE: 1,150,045 - MAE: 866,138 - R2: 0.5865 -
Epoch 76/200 - Loss: 1.6345 - RMSE: 1,148,523 - MAE: 865,099 - R2: 0.5876 -
Epoch 77/200 - Loss: 1.6728 - RMSE: 1,147,302 - MAE: 864,322 - R2: 0.5885 -
Epoch 78/200 - Loss: 1.7033 - RMSE: 1,146,065 - MAE: 863,594 - R2: 0.5893 -
Epoch 79/200 - Loss: 1.6448 - RMSE: 1,144,917 - MAE: 862,859 - R2: 0.5902 -
Epoch 80/200 - Loss: 1.5533 - RMSE: 1,144,724 - MAE: 862,764 - R2: 0.5903 -
Epoch 81/200 - Loss: 1.6412 - RMSE: 1,143,171 - MAE: 861,733 - R2: 0.5914 -
Epoch 82/200 - Loss: 1.6703 - RMSE: 1,142,259 - MAE: 861,255 - R2: 0.5921 -
Epoch 83/200 - Loss: 1.6728 - RMSE: 1,140,828 - MAE: 860,402 - R2: 0.5931 -
Epoch 84/200 - Loss: 1.6946 - RMSE: 1,139,664 - MAE: 859,788 - R2: 0.5939 -
Epoch 85/200 - Loss: 1.6135 - RMSE: 1,139,448 - MAE: 859,523 - R2: 0.5941 -
Epoch 86/200 - Loss: 1.6321 - RMSE: 1,138,683 - MAE: 859,080 - R2: 0.5946 -
Epoch 87/200 - Loss: 1.5344 - RMSE: 1,138,283 - MAE: 858,676 - R2: 0.5949 -
Epoch 88/200 - Loss: 1.5168 - RMSE: 1,137,656 - MAE: 858,179 - R2: 0.5954 -
Epoch 89/200 - Loss: 1.6331 - RMSE: 1,136,949 - MAE: 857,825 - R2: 0.5959 -
Epoch 90/200 - Loss: 1.6793 - RMSE: 1,135,612 - MAE: 857,060 - R2: 0.5968 -
Epoch 91/200 - Loss: 1.6051 - RMSE: 1,134,802 - MAE: 856,624 - R2: 0.5974 -
Epoch 92/200 - Loss: 1.6726 - RMSE: 1,133,241 - MAE: 855,728 - R2: 0.5985 -
Epoch 93/200 - Loss: 1.6135 - RMSE: 1,132,282 - MAE: 855,059 - R2: 0.5992 -
Epoch 94/200 - Loss: 1.5885 - RMSE: 1,131,459 - MAE: 854,563 - R2: 0.5998 -
Epoch 95/200 - Loss: 1.6798 - RMSE: 1,130,262 - MAE: 853,781 - R2: 0.6006 -
Epoch 96/200 - Loss: 1.7003 - RMSE: 1,128,567 - MAE: 852,702 - R2: 0.6018 -
Epoch 97/200 - Loss: 1.7282 - RMSE: 1,127,121 - MAE: 851,841 - R2: 0.6028 -
Epoch 98/200 - Loss: 1.5845 - RMSE: 1,126,505 - MAE: 851,391 - R2: 0.6032 -
Epoch 99/200 - Loss: 1.6546 - RMSE: 1,124,823 - MAE: 850,420 - R2: 0.6044 -
Epoch 100/200 - Loss: 1.5539 - RMSE: 1,124,403 - MAE: 850,044 - R2: 0.6047 -
Epoch 101/200 - Loss: 1.6420 - RMSE: 1,123,717 - MAE: 849,608 - R2: 0.6052 -
Epoch 102/200 - Loss: 1.6308 - RMSE: 1,122,994 - MAE: 849,120 - R2: 0.6057 -
Epoch 103/200 - Loss: 1.6863 - RMSE: 1,121,527 - MAE: 848,272 - R2: 0.6067 -
Epoch 104/200 - Loss: 1.6639 - RMSE: 1,120,698 - MAE: 847,765 - R2: 0.6073 -
Epoch 105/200 - Loss: 1.6308 - RMSE: 1,120,709 - MAE: 847,736 - R2: 0.6073 -
Epoch 106/200 - Loss: 1.6742 - RMSE: 1,119,667 - MAE: 847,126 - R2: 0.6080 -
Epoch 107/200 - Loss: 1.6149 - RMSE: 1,119,165 - MAE: 846,846 - R2: 0.6084 -
Epoch 108/200 - Loss: 1.6499 - RMSE: 1,117,709 - MAE: 846,109 - R2: 0.6094 -
Epoch 109/200 - Loss: 1.6629 - RMSE: 1,116,461 - MAE: 845,444 - R2: 0.6103 -
Epoch 110/200 - Loss: 1.5596 - RMSE: 1,116,867 - MAE: 845,577 - R2: 0.6100 -
Epoch 111/200 - Loss: 1.6571 - RMSE: 1,116,100 - MAE: 845,091 - R2: 0.6105 -
Epoch 112/200 - Loss: 1.6910 - RMSE: 1,115,449 - MAE: 844,768 - R2: 0.6110 -
Epoch 113/200 - Loss: 1.6531 - RMSE: 1,114,417 - MAE: 844,114 - R2: 0.6117 -
Epoch 114/200 - Loss: 1.6625 - RMSE: 1,113,575 - MAE: 843,601 - R2: 0.6123 -
Epoch 115/200 - Loss: 1.6323 - RMSE: 1,112,466 - MAE: 843,006 - R2: 0.6131 -
Epoch 116/200 - Loss: 1.5999 - RMSE: 1,111,920 - MAE: 842,538 - R2: 0.6135 -
Epoch 117/200 - Loss: 1.6101 - RMSE: 1,111,492 - MAE: 842,144 - R2: 0.6138 -
Epoch 118/200 - Loss: 1.6324 - RMSE: 1,110,920 - MAE: 841,802 - R2: 0.6141 -
Epoch 119/200 - Loss: 1.6278 - RMSE: 1,110,747 - MAE: 841,714 - R2: 0.6143 -
Epoch 120/200 - Loss: 1.5871 - RMSE: 1,110,503 - MAE: 841,462 - R2: 0.6144 -
Epoch 121/200 - Loss: 1.6382 - RMSE: 1,109,980 - MAE: 841,106 - R2: 0.6148 -
Epoch 122/200 - Loss: 1.6702 - RMSE: 1,109,158 - MAE: 840,626 - R2: 0.6154 -
Epoch 123/200 - Loss: 1.5750 - RMSE: 1,109,802 - MAE: 840,830 - R2: 0.6149 -
Epoch 124/200 - Loss: 1.6075 - RMSE: 1,109,574 - MAE: 840,637 - R2: 0.6151 -
Epoch 125/200 - Loss: 1.5776 - RMSE: 1,109,050 - MAE: 840,261 - R2: 0.6154 -
Epoch 126/200 - Loss: 1.5882 - RMSE: 1,108,778 - MAE: 840,035 - R2: 0.6156 -
Epoch 127/200 - Loss: 1.6464 - RMSE: 1,108,972 - MAE: 840,319 - R2: 0.6155 -
Epoch 128/200 - Loss: 1.5804 - RMSE: 1,108,023 - MAE: 839,659 - R2: 0.6162 -
Epoch 129/200 - Loss: 1.6601 - RMSE: 1,106,737 - MAE: 839,052 - R2: 0.6170 -
Epoch 130/200 - Loss: 1.7151 - RMSE: 1,105,745 - MAE: 838,569 - R2: 0.6177 -
Epoch 131/200 - Loss: 1.6641 - RMSE: 1,105,228 - MAE: 838,326 - R2: 0.6181 -
Epoch 132/200 - Loss: 1.6086 - RMSE: 1,104,099 - MAE: 837,681 - R2: 0.6189 -
Epoch 133/200 - Loss: 1.6335 - RMSE: 1,103,241 - MAE: 837,311 - R2: 0.6195 -
Epoch 134/200 - Loss: 1.6931 - RMSE: 1,103,011 - MAE: 837,149 - R2: 0.6196 -
Epoch 135/200 - Loss: 1.5924 - RMSE: 1,103,701 - MAE: 837,436 - R2: 0.6191 -
Epoch 136/200 - Loss: 1.6488 - RMSE: 1,102,307 - MAE: 836,793 - R2: 0.6201 -
Epoch 137/200 - Loss: 1.6143 - RMSE: 1,102,004 - MAE: 836,651 - R2: 0.6203 -
Epoch 138/200 - Loss: 1.6191 - RMSE: 1,102,087 - MAE: 836,534 - R2: 0.6203 -
Epoch 139/200 - Loss: 1.6422 - RMSE: 1,101,830 - MAE: 836,343 - R2: 0.6204 -
Epoch 140/200 - Loss: 1.5912 - RMSE: 1,102,693 - MAE: 836,670 - R2: 0.6198 -
Epoch 141/200 - Loss: 1.5981 - RMSE: 1,101,672 - MAE: 836,178 - R2: 0.6205 -
Epoch 142/200 - Loss: 1.6632 - RMSE: 1,100,624 - MAE: 835,851 - R2: 0.6213 -
Epoch 143/200 - Loss: 1.5749 - RMSE: 1,099,677 - MAE: 835,404 - R2: 0.6219 -
Epoch 144/200 - Loss: 1.6853 - RMSE: 1,098,452 - MAE: 834,924 - R2: 0.6228 -
Epoch 145/200 - Loss: 1.6021 - RMSE: 1,099,165 - MAE: 835,188 - R2: 0.6223 -
Epoch 146/200 - Loss: 1.6534 - RMSE: 1,099,236 - MAE: 835,181 - R2: 0.6222 -
Epoch 147/200 - Loss: 1.6323 - RMSE: 1,097,602 - MAE: 834,329 - R2: 0.6233 -
Epoch 148/200 - Loss: 1.6338 - RMSE: 1,098,133 - MAE: 834,398 - R2: 0.6230 -
Epoch 149/200 - Loss: 1.6308 - RMSE: 1,097,668 - MAE: 834,161 - R2: 0.6233 -
Epoch 150/200 - Loss: 1.6713 - RMSE: 1,097,263 - MAE: 833,960 - R2: 0.6236 -
Epoch 151/200 - Loss: 1.6778 - RMSE: 1,096,079 - MAE: 833,363 - R2: 0.6244 -
Epoch 152/200 - Loss: 1.6015 - RMSE: 1,096,496 - MAE: 833,615 - R2: 0.6241 -
Epoch 153/200 - Loss: 1.6604 - RMSE: 1,095,606 - MAE: 833,077 - R2: 0.6247 -
Epoch 154/200 - Loss: 1.5945 - RMSE: 1,095,112 - MAE: 832,722 - R2: 0.6251 -
Epoch 155/200 - Loss: 1.5894 - RMSE: 1,095,484 - MAE: 832,841 - R2: 0.6248 -
Epoch 156/200 - Loss: 1.5754 - RMSE: 1,094,601 - MAE: 832,366 - R2: 0.6254 -
Epoch 157/200 - Loss: 1.6584 - RMSE: 1,093,698 - MAE: 831,954 - R2: 0.6260 -
Epoch 158/200 - Loss: 1.6693 - RMSE: 1,094,391 - MAE: 832,099 - R2: 0.6255 -
Epoch 159/200 - Loss: 1.5750 - RMSE: 1,095,078 - MAE: 832,245 - R2: 0.6251 -
Epoch 160/200 - Loss: 1.6569 - RMSE: 1,094,297 - MAE: 831,945 - R2: 0.6256 -
Epoch 161/200 - Loss: 1.6267 - RMSE: 1,093,346 - MAE: 831,512 - R2: 0.6263 -
Epoch 162/200 - Loss: 1.5833 - RMSE: 1,093,696 - MAE: 831,500 - R2: 0.6260 -
Epoch 163/200 - Loss: 1.5995 - RMSE: 1,093,523 - MAE: 831,296 - R2: 0.6261 -
Epoch 164/200 - Loss: 1.6667 - RMSE: 1,091,859 - MAE: 830,707 - R2: 0.6273 -
Epoch 165/200 - Loss: 1.6356 - RMSE: 1,091,311 - MAE: 830,408 - R2: 0.6277 -
Epoch 166/200 - Loss: 1.6746 - RMSE: 1,090,316 - MAE: 829,932 - R2: 0.6283 -
Epoch 167/200 - Loss: 1.6270 - RMSE: 1,089,196 - MAE: 829,537 - R2: 0.6291 -
Epoch 168/200 - Loss: 1.6238 - RMSE: 1,089,013 - MAE: 829,466 - R2: 0.6292 -
Epoch 169/200 - Loss: 1.5834 - RMSE: 1,089,290 - MAE: 829,481 - R2: 0.6290 -
Epoch 170/200 - Loss: 1.6751 - RMSE: 1,088,009 - MAE: 828,962 - R2: 0.6299 -
Epoch 171/200 - Loss: 1.6078 - RMSE: 1,087,475 - MAE: 828,632 - R2: 0.6303 -
Epoch 172/200 - Loss: 1.6055 - RMSE: 1,087,325 - MAE: 828,590 - R2: 0.6304 -
Epoch 173/200 - Loss: 1.6506 - RMSE: 1,086,567 - MAE: 828,131 - R2: 0.6309 -
Epoch 174/200 - Loss: 1.6638 - RMSE: 1,086,802 - MAE: 828,203 - R2: 0.6307 -
Epoch 175/200 - Loss: 1.5875 - RMSE: 1,086,930 - MAE: 828,216 - R2: 0.6306 -
Epoch 176/200 - Loss: 1.6197 - RMSE: 1,086,443 - MAE: 828,156 - R2: 0.6310 -
Epoch 177/200 - Loss: 1.6268 - RMSE: 1,085,852 - MAE: 827,803 - R2: 0.6314 -
Epoch 178/200 - Loss: 1.6347 - RMSE: 1,085,962 - MAE: 827,682 - R2: 0.6313 -
Epoch 179/200 - Loss: 1.6377 - RMSE: 1,085,397 - MAE: 827,331 - R2: 0.6317 -
Epoch 180/200 - Loss: 1.6719 - RMSE: 1,085,081 - MAE: 827,131 - R2: 0.6319 -
Epoch 181/200 - Loss: 1.5917 - RMSE: 1,085,569 - MAE: 827,157 - R2: 0.6316 -
Epoch 182/200 - Loss: 1.6457 - RMSE: 1,085,089 - MAE: 826,842 - R2: 0.6319 -
Epoch 183/200 - Loss: 1.6149 - RMSE: 1,083,905 - MAE: 826,423 - R2: 0.6327 -
Epoch 184/200 - Loss: 1.5834 - RMSE: 1,083,839 - MAE: 826,292 - R2: 0.6327 -
Epoch 185/200 - Loss: 1.6662 - RMSE: 1,083,301 - MAE: 826,087 - R2: 0.6331 -
Epoch 186/200 - Loss: 1.6177 - RMSE: 1,082,962 - MAE: 825,886 - R2: 0.6333 -
Epoch 187/200 - Loss: 1.6596 - RMSE: 1,082,809 - MAE: 825,835 - R2: 0.6334 -
Epoch 188/200 - Loss: 1.6837 - RMSE: 1,082,460 - MAE: 825,659 - R2: 0.6337 -
Epoch 189/200 - Loss: 1.6711 - RMSE: 1,082,386 - MAE: 825,580 - R2: 0.6337 -
Epoch 190/200 - Loss: 1.6266 - RMSE: 1,082,482 - MAE: 825,469 - R2: 0.6337 -
Epoch 191/200 - Loss: 1.5956 - RMSE: 1,081,890 - MAE: 825,081 - R2: 0.6341 -
Epoch 192/200 - Loss: 1.6869 - RMSE: 1,080,533 - MAE: 824,481 - R2: 0.6350 -
Epoch 193/200 - Loss: 1.6811 - RMSE: 1,080,012 - MAE: 824,179 - R2: 0.6353 -
Epoch 194/200 - Loss: 1.6065 - RMSE: 1,080,019 - MAE: 824,030 - R2: 0.6353 -
Epoch 195/200 - Loss: 1.6530 - RMSE: 1,079,866 - MAE: 823,770 - R2: 0.6354 -
Epoch 196/200 - Loss: 1.6754 - RMSE: 1,079,183 - MAE: 823,409 - R2: 0.6359 -
Epoch 197/200 - Loss: 1.6654 - RMSE: 1,079,033 - MAE: 823,165 - R2: 0.6360 -
Epoch 198/200 - Loss: 1.6781 - RMSE: 1,079,141 - MAE: 823,116 - R2: 0.6359 -
Epoch 199/200 - Loss: 1.6251 - RMSE: 1,077,917 - MAE: 822,575 - R2: 0.6367 -
Epoch 200/200 - Loss: 1.6335 - RMSE: 1,076,832 - MAE: 822,280 - R2: 0.6375 -